#!/usr/bin/env python3
"""
replay.py - local ride replay / UI debug harness for the AgentMS3 tracker.

It rebuilds a throwaway SQLite DB from RECORDED frames and launches the real
webapp against it, so you can open the dashboard locally and see exactly what
the UI shows for a past ride -- and, because it re-feeds the raw telemetry
through the REAL carserver decoder, any change you make to carserver.py's
parsing/event-detection shows up on the next replay run. This is the debug
loop for decoding new events (0x0209 transponder/parking-brake/Event#NN, etc.)
and for the "why didn't the label display" kind of questions.

How it works
------------
* position / journal / kv are COPIED from the source DB (GPS frames aren't
  stored as telemetry, so the track can't be re-derived -- we copy it).
* telemetry rows (recv_ts, type, hex) are RE-FED through CarServer.store()
  with the clock monkeypatched to each frame's original timestamp, so events,
  status kv and metrics are regenerated by the current decoder.

Usage
-----
  # 1. get a consistent snapshot of the live DB onto this machine (once per test):
  python replay.py --pull                      # scp a VACUUMed snapshot to ./car_snap.db

  # 2. replay a ride window (UTC times; Athens local = UTC+3) and open the UI:
  python replay.py --from "2026-07-07 12:43" --to "2026-07-07 13:01"

  # replay everything in the snapshot:
  python replay.py

  # just build the replay DB, don't launch the webapp:
  python replay.py --from ... --to ... --no-serve

Then open http://localhost:3399/ . The track defaults to "last 1h" relative to
now; for an older ride click the clock (Track period) -> Custom and paste the
from/to that this script prints.
"""
import argparse
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_HOST = "root@173.242.49.128"
DEFAULT_REMOTE_DB = "/root/captures/car.db"


def pull_snapshot(host, remote_db, dest):
    """Make a consistent hot-backup snapshot on the server (folds in the WAL), then scp it."""
    snap = "/tmp/car_snap.db"
    py = ("import sqlite3,os; os.path.exists('%s') and os.remove('%s'); "
          "s=sqlite3.connect('%s'); d=sqlite3.connect('%s'); s.backup(d); s.close(); d.close()"
          % (snap, snap, remote_db, snap))
    print("[pull] creating snapshot on %s ..." % host)
    subprocess.check_call(["ssh", host, 'python3 -c "%s"' % py])
    print("[pull] copying -> %s" % dest)
    subprocess.check_call(["scp", "%s:%s" % (host, snap), dest])
    print("[pull] done.")


def build_replay_db(src_path, workdir, lo, hi):
    """Create workdir/car.db: copy position/journal/kv, then replay telemetry
    through the real CarServer decoder. Returns the replay db path."""
    # fresh work dir
    if os.path.isdir(workdir):
        shutil.rmtree(workdir, ignore_errors=True)
    os.makedirs(workdir, exist_ok=True)

    sys.path.insert(0, HERE)
    import carserver  # noqa: E402  (imported here so --pull works without the module side effects)

    # A CarServer instance with no networking: __init__ only sets up the DB + files.
    cs = carserver.CarServer(0, workdir, relay=False, upstream=None)

    src = sqlite3.connect("file:%s?mode=ro" % src_path, uri=True)

    # 1) copy the GPS track, the raw journal and the current kv snapshot verbatim
    pos = src.execute(
        "SELECT recv_ts,dev_time,lat,lon,speed_knots,course FROM position "
        "WHERE recv_ts BETWEEN ? AND ? ORDER BY id", (lo, hi)).fetchall()
    cs.db.executemany(
        "INSERT INTO position(recv_ts,dev_time,lat,lon,speed_knots,course) VALUES(?,?,?,?,?,?)", pos)
    jr = src.execute("SELECT ts,dir,summary FROM journal WHERE ts BETWEEN ? AND ? ORDER BY id",
                     (lo, hi)).fetchall()
    cs.db.executemany("INSERT INTO journal(ts,dir,summary) VALUES(?,?,?)", jr)
    for k, v, u in src.execute("SELECT k,v,updated FROM kv").fetchall():
        cs.db.execute("INSERT OR REPLACE INTO kv(k,v,updated) VALUES(?,?,?)", (k, v, u))
    cs.db.commit()

    # 2) re-feed telemetry through the real decoder with the clock set to each frame's ts
    clock = [None]
    carserver.now = lambda: clock[0]           # store()/_detect_events use module-global now()
    tel = src.execute("SELECT recv_ts,type,hex FROM telemetry WHERE recv_ts BETWEEN ? AND ? ORDER BY id",
                      (lo, hi)).fetchall()
    errs = 0
    for ts, typ, hx in tel:
        clock[0] = ts
        try:
            cs.store({"typ": int(typ, 16), "data": bytes.fromhex(hx), "frm": 0})
        except Exception as e:
            errs += 1
            if errs <= 5:
                print("  [replay] store error @%s %s: %s" % (ts, typ, e))
    cs.db.commit()

    dbpath = cs.dbpath
    # summary
    c = cs.db.cursor()
    print("\n=== replay DB built: %s ===" % dbpath)
    for tbl in ("position", "telemetry", "journal", "events", "metrics"):
        print("  %-9s %d rows" % (tbl, c.execute("SELECT COUNT(*) FROM %s" % tbl).fetchone()[0]))
    print("  --- events (regenerated by the current decoder) ---")
    for ts, kind, ev in c.execute("SELECT ts,kind,event FROM events ORDER BY id").fetchall():
        print("    %s  %-9s %s" % (ts[11:19], kind, ev))
    src.close()
    cs.db.close()
    return dbpath


def main():
    ap = argparse.ArgumentParser(description="Replay recorded rides through the webapp for local debugging.")
    ap.add_argument("--src", default=os.path.join(HERE, "car_snap.db"),
                    help="local source DB (default ./car_snap.db; use --pull to fetch it)")
    ap.add_argument("--from", dest="frm", default="0000-00-00 00:00",
                    help="window start, UTC 'YYYY-MM-DD HH:MM' (Athens local = UTC+3)")
    ap.add_argument("--to", dest="to", default="9999-99-99 99:99", help="window end, UTC")
    ap.add_argument("--port", type=int, default=3399)
    ap.add_argument("--pull", action="store_true", help="scp a fresh snapshot from the server into --src, then replay")
    ap.add_argument("--host", default=DEFAULT_HOST)
    ap.add_argument("--remote-db", default=DEFAULT_REMOTE_DB)
    ap.add_argument("--no-serve", action="store_true", help="build the replay DB but don't launch the webapp")
    ap.add_argument("--workdir", default=os.path.join(tempfile.gettempdir(), "agentms3_replay"))
    a = ap.parse_args()

    if a.pull:
        pull_snapshot(a.host, a.remote_db, a.src)
    if not os.path.exists(a.src):
        sys.exit("source DB not found: %s   (run with --pull first)" % a.src)

    dbpath = build_replay_db(a.src, a.workdir, a.frm, a.to)
    print("\nTrack range to paste into the dashboard (clock -> Custom): %s  ->  %s" % (a.frm, a.to))

    if a.no_serve:
        print("\n--no-serve: open the webapp yourself with:\n  python webapp.py --db \"%s\" --port %d" % (dbpath, a.port))
        return
    print("\n=== launching webapp -> http://localhost:%d/  (Ctrl+C to stop) ===\n" % a.port)
    proc = subprocess.Popen([sys.executable, os.path.join(HERE, "webapp.py"),
                             "--db", dbpath, "--port", str(a.port)])
    try:
        proc.wait()
    except KeyboardInterrupt:
        proc.terminate()


if __name__ == "__main__":
    main()
